"""
Renko brick engine.

Renko brick construction is mathematically identical to P&F column
construction with reversal_boxes=2 (NOT 1 — see correction below).
Confirmed against the book's own fully worked construction exercise
(Table 1.1-1.5, brick value 10): a bearish reversal brick only prints
once price closes at or below the LOW of the previous brick, e.g. with
an up-run extreme at 120 (book's step 8, price 99.90), the reversal
brick doesn't print at 110 (one box down) — it prints at 100, two full
box-levels below the extreme. The book states this explicitly for its
brick-value-5 illustration too: "the price has to move down to 105 ...
which is the low price of the PREVIOUS brick" (i.e. two bricks back
from the current extreme, not one). A single-box move only ever
extends/opens the current brick; a two-box move against the trend is
what flips direction.

Source: "Renko Charts" (Prashant Shah) — Ch. 1, Table 1.1-1.5.
See tests/test_renko_engine.py for the step-by-step regression test
built from that exercise (traced by hand against this module's logic,
not generated by running it).

This module intentionally holds no new construction logic — it is a
thin, Renko-flavoured wrapper around pnf_engine.BoxSettings/build_columns,
which already implements every rule (box-price tracking, symmetric
reversal, direction-dependent box level, absolute-grid anchoring) that
Renko brick construction also needs. "Column" in the reused engine maps
1:1 to "brick" here; this module speaks in "brick" everywhere.
"""
from __future__ import annotations

from typing import Optional

from pnf_engine import BoxSettings, Column, build_columns, current_state

Brick = Column  # Renko-facing alias; same shape, direction/start_level/end_level/anchor/box_count


def brick_settings(box_pct: Optional[float] = None, box_value: Optional[float] = None) -> BoxSettings:
    """Renko reverses once price crosses 2 full box-levels against the
    extreme (the low/high of the PREVIOUS brick, not the current one —
    see module docstring). reversal_boxes=2 is the defining value that
    distinguishes Renko from P&F's usual reversal_boxes=3."""
    return BoxSettings(reversal_boxes=2, box_pct=box_pct, box_value=box_value)


def build_bricks(prices: list, settings: BoxSettings) -> list[Brick]:
    return build_columns(prices, settings)


def brick_state(prices: list, box_pct: float = None, box_value: float = None) -> dict:
    """Convenience one-shot: build the bricks and return just the
    current state ({"direction": "up"|"down"|None, "extreme_price": ...})."""
    settings = brick_settings(box_pct=box_pct, box_value=box_value)
    return current_state(build_bricks(prices, settings), settings)


from dataclasses import dataclass


@dataclass
class BrickUnit:
    """One single printed brick (one box), unlike Column/Brick above
    which bundles a whole same-direction run into one object (the way
    P&F bundles a run of same-direction boxes into one "column"). Renko
    pattern rules (One-Back, Two-Back, Anchor Bricks, etc.) are stated
    in the book per individual brick, not per run, so pattern detection
    walks this flat list rather than the run-level Column list."""
    direction: str  # "up" | "down"
    level: int       # this brick's own box level (its close)
    run_index: int   # which Column/run this brick belongs to
    position_in_run: int  # 0-based position of this brick within its run
    run_length: int  # total bricks in this brick's run
    anchor: float = 1.0


def expand_to_bricks(columns: list) -> list[BrickUnit]:
    """Flattens the run-bundled Column list into one BrickUnit per
    printed box, in chart order — e.g. a Column spanning 5 boxes up
    becomes 5 separate up BrickUnits at consecutive levels. This is the
    representation every brick-level pattern detector in
    renko_patterns.py operates on."""
    out: list[BrickUnit] = []
    for run_index, c in enumerate(columns):
        n = c.box_count
        step = 1 if c.direction == "up" else -1
        for pos in range(n):
            level = c.start_level + step * pos
            out.append(BrickUnit(c.direction, level, run_index, pos, n, c.anchor))
    return out


def brick_close_prices(bricks: list, settings: BoxSettings) -> list:
    """One price per brick, per the book's own convention for indicator
    input (Ch.7): the close of a bullish brick is its HIGH (end_level),
    the close of a bearish brick is its LOW (end_level) — i.e. simply
    the brick's own end_level in both cases, converted to a real price."""
    return [settings.price_at(b.end_level, b.anchor) for b in bricks]
