"""Regression tests for the P&F pattern/indicator libraries.

Where the book ("Trading The Markets The Point & Figure Way", Prashant
Shah) gives an explicit worked example with real numbers, that example is
transcribed here BY HAND from the text — not generated by running the
code — so these tests are genuine ground truth and not a snapshot of
whatever the implementation happens to do. That is the same discipline
tests/test_pnf_engine.py already applies to chart construction.

Columns are constructed directly rather than via build_columns(): the
construction rules already have their own regression suite, and building
them by hand lets each pattern test state exactly the geometry the book
describes (e.g. the High Pole example's X column spanning box-prices
70..140, which is 8 boxes).
"""
import pytest

from pnf_engine import BoxSettings, Column
import pnf_patterns as pf
import pnf_indicators as pi

BOX10 = BoxSettings(reversal_boxes=3, box_value=10.0)


def X(low: int, high: int) -> Column:
    """An X column spanning [low, high] in box levels."""
    return Column("up", low, high, 1.0)


def O(high: int, low: int) -> Column:
    """An O column spanning [low, high], travelling downward."""
    return Column("down", high, low, 1.0)


# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------


def test_top_bottom_and_boxcount_are_direction_independent():
    assert pf.top(X(7, 14)) == 14 and pf.bottom(X(7, 14)) == 7
    assert pf.top(O(14, 7)) == 14 and pf.bottom(O(14, 7)) == 7
    # Book 2.1 High Pole example: "The total number of boxes in the column
    # of X is 8" for a column spanning box-prices 70 to 140 (box = 10).
    assert X(7, 14).box_count == 8
    # "Mid-box-price of column: (High Box-price + Low Box-price)/2" -> 105.
    assert pf.mid_level(X(7, 14)) == 10.5
    assert BOX10.price_at(pf.mid_level(X(7, 14))) == 105.0
    # On an absolute box-value chart the two agree exactly.
    assert pf.mid_price(X(7, 14), BOX10) == 105.0


def test_mid_price_is_the_arithmetic_mean_of_prices_on_a_log_chart():
    """Ground truth from the real platform's commentary panel (NIFTY
    24400 CE, 3% x 3, 31-Jul-2026): a column running 291.57..309.33 is
    reported MidVal 300.45, and one running 283.08..318.61 is reported
    300.85. Both are the ARITHMETIC mean of the two prices.

    Averaging box LEVELS instead and converting back yields the geometric
    mean (300.32 for both of those columns) — visibly wrong, and it
    biases every Pole's 50%-retracement test. This is the bug that check
    caught."""
    s = BoxSettings(reversal_boxes=3, box_pct=0.03)
    # The real column is 3 boxes: 291.57 -> 300.32 -> 309.33. Derive the
    # top from the bottom rather than resolving each price separately,
    # since either rounding direction can slip a box on an exact boundary.
    lo = s.level_down(291.57)
    hi = lo + 2
    col = Column("down", hi, lo, 1.0)
    assert s.price_at(lo) == pytest.approx(291.57, abs=0.02)
    assert s.price_at(hi) == pytest.approx(309.33, abs=0.02)
    assert pf.mid_price(col, s) == pytest.approx(300.45, abs=0.02)
    # The level-space midpoint is the geometric mean — not what the
    # platform reports.
    assert s.price_at(pf.mid_level(col)) == pytest.approx(300.32, abs=0.02)


# ---------------------------------------------------------------------------
# Basic signals
# ---------------------------------------------------------------------------


def test_basic_signals_compare_against_the_previous_same_direction_column():
    cols = [X(1, 5), O(4, 2), X(3, 6)]
    assert pf.is_double_top_buy(cols, 2)
    assert pf.breakout_level(cols, 2) == 6  # one box past the prior X high of 5
    cols = [O(5, 1), X(2, 4), O(3, 0)]
    assert pf.is_double_bottom_sell(cols, 2)
    assert pf.breakout_level(cols, 2) == 0


def test_equal_high_is_not_a_breakout():
    cols = [X(1, 5), O(4, 2), X(3, 5)]
    assert not pf.is_double_top_buy(cols, 2)


# ---------------------------------------------------------------------------
# 2.1 Triple Top / Bottom — "strictly a five-column formation"
# ---------------------------------------------------------------------------


def test_triple_top_buy_requires_two_equal_highs_then_breakout():
    cols = [X(1, 6), O(5, 3), X(4, 6), O(5, 2), X(3, 8)]
    p = pf.detect_triple_top_buy(cols, 4)
    assert p is not None and p.bias == "bullish"
    assert p.trigger_level == 7          # one box above the shared high of 6
    assert p.start_index == 0
    # "the pattern does not fail unless price falls below the lowest O in
    # the pattern" — the lowest print here is 1, so failing it needs a
    # print at 0, one box below.
    assert p.failure_level == 0


def test_triple_top_rejects_unequal_shoulders():
    cols = [X(1, 6), O(5, 3), X(4, 7), O(6, 2), X(3, 9)]
    assert pf.detect_triple_top_buy(cols, 4) is None


def test_triple_bottom_sell_mirrors():
    cols = [O(9, 4), X(5, 7), O(6, 4), X(5, 8), O(7, 2)]
    p = pf.detect_triple_bottom_sell(cols, 4)
    assert p is not None and p.bias == "bearish"
    assert p.trigger_level == 3
    assert p.failure_level == 10


# ---------------------------------------------------------------------------
# 2.1 Traps — "strictly four-column patterns"
# ---------------------------------------------------------------------------


def test_bull_trap_is_a_sell_immediately_after_a_buy():
    # O,X(buy),O(sell) preceded by an O to compare against.
    cols = [O(8, 4), X(5, 7), O(6, 3), X(4, 9), O(8, 2)]
    assert pf.is_double_top_buy(cols, 3)
    p = pf.detect_bull_trap(cols, 4)
    assert p is not None and p.bias == "bearish"
    # "the basic Buy-Sell signal and pattern failure level is the same" —
    # it fails on the next Double Top Buy, above the trapped X column.
    assert p.failure_level == 10


def test_bear_trap_is_a_buy_immediately_after_a_sell():
    cols = [X(2, 8), O(7, 4), X(5, 6), O(5, 3), X(4, 7)]
    assert pf.is_double_bottom_sell(cols, 3)
    p = pf.detect_bear_trap(cols, 4)
    assert p is not None and p.bias == "bullish"
    assert p.failure_level == 2


# ---------------------------------------------------------------------------
# 2.1 Poles — the book's own worked examples, numbers transcribed verbatim
# ---------------------------------------------------------------------------


def test_high_pole_matches_the_books_worked_example():
    """Book 2.1: Double Top Buy at box-price 100; price travels five boxes
    to 140; the X column spans 70..140 (8 boxes) so its mid-price is 105;
    "Immediate box-price below 105 is 100, so that becomes the box-price
    at which High Pole will get formed"."""
    cols = [X(4, 9), O(8, 6), X(7, 14), O(13, 10)]
    p = pf.detect_high_pole(cols, 3)
    assert p is not None and p.bias == "bearish"
    assert p.meta["boxes_after_breakout"] == 5      # "traveled five boxes"
    assert p.meta["mid_level"] == 10.5              # box-price 105
    assert BOX10.price_at(p.trigger_level) == 100.0
    # "pattern fails if price goes above the [high of the breakout column]"
    assert BOX10.price_at(p.failure_level) == 150.0


def test_low_pole_matches_the_books_worked_example():
    """Book 2.1: Double Bottom Sell at box-price 90, five boxes down to
    50; the O column spans 50..120 (8 boxes), mid 85; "Immediate box-price
    above 85 is 90, which becomes the box-price above which the Low Pole
    will get formed"."""
    cols = [O(15, 10), X(11, 12), O(12, 5), X(6, 9)]
    p = pf.detect_low_pole(cols, 3)
    assert p is not None and p.bias == "bullish"
    assert p.meta["boxes_after_breakout"] == 5
    assert p.meta["mid_level"] == 8.5               # box-price 85
    assert BOX10.price_at(p.trigger_level) == 90.0
    assert BOX10.price_at(p.failure_level) == 40.0


def test_pole_needs_the_full_five_box_move():
    # Only four boxes past the breakout -> not a pole.
    cols = [X(4, 10), O(9, 6), X(7, 14), O(13, 10)]
    assert pf.detect_high_pole(cols, 3) is None


def test_pole_retracement_must_be_in_the_immediately_following_column():
    """Book: "the immediately following column of O". A shallow next
    column disqualifies it even if a later column retraces deeper — this
    is the deliberate divergence from blackbox_prism_alpha's looser
    strategy-local reading."""
    cols = [X(4, 9), O(8, 6), X(7, 14), O(13, 12), X(13, 14), O(13, 8)]
    assert pf.detect_high_pole(cols, 3) is None


def test_hundred_percent_pole_is_also_a_pole_and_a_trap():
    """Book 2.2: "a bullish 100% Pole is a Low Pole, a Bear Trap as well
    as a Double Top Buy pattern" — all three must report together."""
    cols = [O(15, 10), X(11, 12), O(12, 5), X(6, 13)]
    assert pf.detect_low_pole(cols, 3) is not None
    assert pf.detect_bear_trap(cols, 3) is not None
    assert pf.is_double_top_buy(cols, 3)
    p = pf.detect_bullish_100_pole(cols, 3)
    assert p is not None and p.bias == "bullish"


# ---------------------------------------------------------------------------
# 2.1 Inside columns / Triangles
# ---------------------------------------------------------------------------


def test_inside_column_needs_both_edges_inside():
    cols = [X(1, 10), O(9, 2)]
    assert pf.is_inside_column(cols, 1)
    cols = [X(1, 10), O(9, 0)]
    assert not pf.is_inside_column(cols, 1)


def test_three_column_triangle_locks_on_the_next_column():
    """Book 2.1: two consecutive inside columns make a three-column
    triangle, which "gets locked over appearance of fourth column"."""
    cols = [X(1, 12), O(11, 3), X(4, 10), O(9, 6)]
    p = pf.detect_triangle(cols, 3)
    assert p is not None and p.bias == "neutral"
    assert p.meta["inside_columns"] == 2
    assert p.label == "3-Column Triangle"


def test_triangle_50_rule_rejects_a_lopsided_series():
    # Column 1 is more than double column 2 -> fails the optional rule.
    cols = [X(0, 40), O(39, 1), X(2, 20), O(19, 12)]
    cfg = pf.PatternConfig(triangle_50_rule=True)
    assert pf.detect_triangle(cols, 3, cfg) is None
    assert pf.detect_triangle(cols, 3) is not None  # rule off by default


# ---------------------------------------------------------------------------
# 2.2 Broadening / Pattern Reversed / Catapult
# ---------------------------------------------------------------------------


def test_bullish_broadening_is_a_buy_after_a_bull_trap():
    cols = [O(8, 4), X(5, 7), O(6, 3), X(4, 9), O(8, 2), X(3, 10)]
    assert pf.detect_bull_trap(cols, 4) is not None
    p = pf.detect_bullish_broadening(cols, 5)
    assert p is not None and p.bias == "bullish"
    assert p.failure_level == 1  # below the lowest O of the formation


def test_bearish_pattern_reversed_is_a_bullish_signal():
    """Book 2.2: "Bearish pattern that reversed is a bullish pattern" — a
    Buy after two consecutive Sells, with no Buy earlier in the six."""
    cols = [X(6, 9), O(8, 5), X(6, 7), O(6, 3), X(4, 6), O(5, 1), X(2, 8)]
    assert pf.is_double_bottom_sell(cols, 5) and pf.is_double_bottom_sell(cols, 3)
    p = pf.detect_bearish_pattern_reversed(cols, 6)
    assert p is not None and p.bias == "bullish"


def test_pattern_reversed_rejected_when_a_buy_came_first():
    # The middle X column breaks out -> that is a Bear Trap sequence, not
    # a pattern-reversed ("column 3 or 5 shouldn't be a Bull Trap").
    cols = [X(6, 9), O(8, 5), X(6, 10), O(6, 3), X(4, 6), O(5, 1), X(2, 8)]
    assert pf.detect_bearish_pattern_reversed(cols, 6) is None


def test_bullish_catapult_is_a_follow_through_to_a_triple_top():
    cols = [X(1, 6), O(5, 3), X(4, 6), O(5, 2), X(3, 8), O(7, 5), X(6, 9)]
    assert pf.detect_triple_top_buy(cols, 4) is not None
    p = pf.detect_bullish_catapult(cols, 6)
    assert p is not None and p.bias == "bullish"


def test_catapult_rejected_when_the_pullback_made_a_sell_signal():
    cols = [X(1, 6), O(5, 3), X(4, 6), O(5, 2), X(3, 8), O(7, 1), X(2, 9)]
    assert pf.detect_bullish_catapult(cols, 6) is None


# ---------------------------------------------------------------------------
# 2.6 / 2.7 — Turtle, Super pattern, Weak breakout
# ---------------------------------------------------------------------------


def test_turtle_breakout_counts_same_direction_columns_not_indices():
    cols = []
    for n in range(10):
        cols.append(X(n, n + 2))
        cols.append(O(n + 1, n))
    cols.append(X(1, 99))
    cfg = pf.PatternConfig(turtle_columns=10)
    p = pf.detect_turtle_breakout(cols, len(cols) - 1, cfg)
    assert p is not None and p.bias == "bullish"
    assert p.meta["columns"] == 10


def test_super_pattern_needs_a_long_thrust_and_a_shallow_pullback():
    """Book 2.7: buy signal, >=10 boxes after it, an immediate O column of
    <=4 boxes, then a follow-through buy."""
    cols = [X(1, 5), O(4, 2), X(3, 16), O(15, 13), X(14, 18)]
    p = pf.detect_super_pattern(cols, 4)
    assert p is not None and p.bias == "bullish"
    assert p.meta["thrust_boxes"] == 11
    assert p.meta["pullback_boxes"] == 3
    assert p.failure_level == 12  # one box under the shallow pullback


def test_super_pattern_rejects_a_deep_pullback():
    cols = [X(1, 5), O(4, 2), X(3, 16), O(15, 8), X(9, 18)]
    assert pf.detect_super_pattern(cols, 4) is None


def test_weak_breakout_is_a_stalled_signal_that_flips():
    """Book 2.7: "only one or two boxes of X after a Double Top Buy signal
    and if the price flips to a column of O thereafter"."""
    cols = [X(1, 5), O(4, 2), X(3, 7), O(6, 4)]
    p = pf.detect_weak_breakout(cols, 3)
    assert p is not None
    assert p.name == "weak_bullish_breakout"
    assert p.meta["boxes_after_breakout"] == 2
    # A strong breakout is not weak.
    cols = [X(1, 5), O(4, 2), X(3, 12), O(11, 4)]
    assert pf.detect_weak_breakout(cols, 3) is None


# ---------------------------------------------------------------------------
# 2.7 — basic-signal variants
# ---------------------------------------------------------------------------


def test_classify_basic_signal_partitions_every_buy():
    # Rising O before the buy -> Rising Double Top Buy.
    cols = [X(1, 6), O(5, 2), X(3, 5), O(4, 3), X(4, 7)]
    assert pf.classify_basic_signal(cols, 4)["variant"] == "rising"
    # O at the same level -> Double Top Buy after Support.
    cols = [X(1, 6), O(5, 3), X(4, 5), O(4, 3), X(4, 7)]
    assert pf.classify_basic_signal(cols, 4)["variant"] == "after_support"
    # Sell then buy -> Bear Trap.
    cols = [X(2, 8), O(7, 4), X(5, 6), O(5, 3), X(4, 7)]
    assert pf.classify_basic_signal(cols, 4)["variant"] == "bear_trap"


# ---------------------------------------------------------------------------
# 2.3 / 2.8 — Follow-through and failure
# ---------------------------------------------------------------------------


def test_follow_through_may_come_later_but_not_after_failure():
    cols = [X(1, 6), O(5, 3), X(4, 6), O(5, 2), X(3, 8)]
    trip = pf.detect_triple_top_buy(cols, 4)
    # No follow-through yet.
    assert pf.find_follow_through(cols, trip) is None
    # A later Double Top Buy, pattern still intact -> follow-through.
    later = cols + [O(7, 5), X(6, 10)]
    ft = pf.find_follow_through(later, trip)
    assert ft is not None and ft.index == 6 and ft.bias == "bullish"
    # If price breaks the pattern's low first, no follow-through.
    failed = cols + [O(7, 0), X(1, 12)]
    assert pf.find_follow_through(failed, trip) is None
    assert pf.has_failed(failed, trip) == 5


# ---------------------------------------------------------------------------
# 4.5 — XO indicators
# ---------------------------------------------------------------------------


def test_xo_zone_is_x_boxes_minus_o_boxes():
    cols = [X(0, 4), O(3, 2)]          # 5 X boxes, 2 O boxes
    assert pi.xo_lines(cols, 2)[-1] == {"x": 5, "o": 2}
    assert pi.xo_zone(cols, 2)[-1] == 3
    assert pi.xo_count(cols, 2)[-1] == 7


def test_xo_zone_crossover_fires_only_on_the_zero_line_cross():
    # Window of 2 columns: first pair net negative, next pair net positive.
    cols = [X(0, 1), O(0, -6), X(-5, 6)]
    zone = [v for v in pi.xo_zone(cols, 2) if v is not None]
    assert zone[0] < 0 < zone[1]
    assert pi.xo_zone_crossover(cols, 2) == "bullish"


# ---------------------------------------------------------------------------
# 4.1 / 4.3 — column-based indicators consume one price per column
# ---------------------------------------------------------------------------


def test_column_price_series_use_high_of_x_and_low_of_o():
    cols = [X(1, 5), O(4, 2)]
    assert pi.column_close_levels(cols) == [5, 2]
    assert pi.column_mid_levels(cols) == [3.0, 3.0]
    assert pi.column_close_prices(cols, BOX10) == [50.0, 20.0]


def test_moving_average_is_over_columns_not_bars():
    cols = [X(0, 2), O(1, 0), X(1, 4), O(3, 1)]
    ma = pi.column_moving_average(cols, BOX10, period=2)
    # Closing-price series is [20, 0, 40, 10]; 2-column SMA of the last
    # two columns is (40 + 10) / 2 = 25.
    assert ma[-1] == 25.0
    assert ma[0] is None


# ---------------------------------------------------------------------------
# 3.3 — Counts, against the book's worked arithmetic
# ---------------------------------------------------------------------------


def test_vertical_counts_match_the_books_example():
    """Book 3.3: "5 x 10 x 3 = 150; 150 + 920 = 1070" for the bullish
    count, and "1080 - 150 = 930" for the bearish one, on a 10 x 3 chart."""
    cols = [O(100, 92), X(93, 97)]     # previous O bottom 920; X column of 5 boxes
    c = pi.vertical_count(cols, 1, BOX10)
    assert c.bias == "bullish" and c.meta["boxes"] == 5
    assert BOX10.price_at(c.target_level) == 1070.0

    cols = [X(100, 108), O(107, 103)]  # previous X top 1080; O column of 5 boxes
    c = pi.vertical_count(cols, 1, BOX10)
    assert c.bias == "bearish" and c.meta["boxes"] == 5
    assert BOX10.price_at(c.target_level) == 930.0


def test_conservative_vertical_count_halves_the_multiplier():
    cols = [O(100, 92), X(93, 97)]
    c = pi.vertical_count(cols, 1, BOX10, conservative=True)
    # 5 boxes x 1.5 = 7.5 boxes, truncated toward the base to 7 so the
    # "conservative" target cannot end up further than the standard one.
    assert BOX10.price_at(c.target_level) == 990.0


def test_horizontal_count_matches_the_books_example():
    """Book 3.3: an 8-column formation on a 10 x 3 chart from a bottom of
    1000 -> "8 x 10 x 3 = 240; 240 + 1000 = 1240"."""
    cols = [O(104, 100), X(101, 103), O(102, 100), X(101, 103),
            O(102, 100), X(101, 103), O(102, 100), X(101, 106)]
    c = pi.horizontal_count(cols, 0, 7, BOX10)
    assert c.bias == "bullish" and c.meta["width"] == 8
    assert BOX10.price_at(c.target_level) == 1240.0


def test_aggressive_horizontal_count_projects_from_the_breakout():
    cols = [O(104, 100), X(101, 103), O(102, 100), X(101, 103),
            O(102, 100), X(101, 103), O(102, 100), X(101, 106)]
    c = pi.horizontal_count(cols, 0, 7, BOX10, aggressive=True)
    # From the exit column's high (1060) rather than the pattern low.
    assert BOX10.price_at(c.target_level) == 1300.0


# ---------------------------------------------------------------------------
# 3.2 — 45-degree trend lines
# ---------------------------------------------------------------------------


def test_bullish_45_line_rises_exactly_one_box_per_column():
    line = pi.TrendLine("bullish", 2, 10, 5)
    assert line.level_at(2) == 10
    assert line.level_at(7) == 15
    line = pi.TrendLine("bearish", 2, 10, 5)
    assert line.level_at(7) == 5


def test_trend_state_flips_when_the_line_is_broken():
    # A steady staircase up keeps the bullish line intact.
    rising = [O(5, 3)] + [X(3 + n, 6 + n) if n % 2 == 0 else O(5 + n, 4 + n)
                          for n in range(8)]
    assert pi.trend_state(rising) == "up"
    # A hard break below the rising line switches to a bearish line.
    broken = rising + [O(10, -20)]
    assert pi.trend_state(broken) == "down"


# ---------------------------------------------------------------------------
# Registry sanity — scanning must never crash on short or odd charts
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("cols", [
    [],
    [X(1, 2)],
    [X(1, 2), O(1, 0)],
    [X(1, 5), O(4, 2), X(3, 6), O(5, 1), X(2, 9), O(8, 3), X(4, 11)],
])
def test_scan_is_total_over_arbitrary_charts(cols):
    found = pf.scan(cols)
    assert all(isinstance(p, pf.Pattern) for p in found)
    assert all(0 <= p.start_index <= p.index < len(cols) for p in found)


def test_prism_alphas_own_column_builder_shares_the_absolute_grid():
    """blackbox_prism_alpha keeps its OWN column-tracking loop (it carries
    per-column timestamps and prices that pnf_engine.Column doesn't), so
    the absolute-grid correction had to be applied there separately — it
    is not inherited. This pins that the two stay in agreement.

    Box sizes differ per module by design (1% there, 0.5%/3% for the
    Index Vector legs, 0.25% default in the Studio); only the CONSTRUCTION
    RULE is shared."""
    import math

    from blackbox_prism_alpha import BOX_PCT, build_pnf_columns

    prices = [100, 103, 101, 106, 104, 110, 107, 113, 109, 116, 112, 119]
    bars = [{"ts": f"3107202609{n:02d}", "close": p} for n, p in enumerate(prices)]

    full = build_pnf_columns(bars)
    trimmed = build_pnf_columns(bars[4:])

    # Trimming the front of the series must not move the box grid.
    assert full[-1]["high_box_price"] == pytest.approx(trimmed[-1]["high_box_price"])
    assert full[-1]["low_box_price"] == pytest.approx(trimmed[-1]["low_box_price"])

    # And every box price sits exactly on a power of (1 + box_pct).
    scale = math.log(1.0 + BOX_PCT)
    for c in full:
        for key in ("high_box_price", "low_box_price"):
            lvl = math.log(c[key]) / scale
            assert lvl == pytest.approx(round(lvl), abs=1e-9)


def test_every_registered_detector_is_callable_at_every_index():
    cols = [X(1, 5), O(4, 2), X(3, 6), O(5, 1), X(2, 9), O(8, 3), X(4, 11)]
    for name, fn in pf.DETECTORS.items():
        for i in range(len(cols)):
            fn(cols, i, pf.DEFAULT_CONFIG)  # must not raise
