"""
Regression test for renko_engine.py, encoding the Renko book's own
fully worked construction exercise verbatim: "Renko Charts" (Prashant
Shah), Ch. 1, Table 1.1-1.5 — a 10-brick-value chart walked through 27
prices, with the book stating explicitly at each step whether a brick
plots and, if so, bullish or bearish.

This is a primary-source ground truth, not a self-check: the price
series and the plot/no-plot outcome at each step are transcribed
directly from the book's own step-by-step tables. The resulting
4-column sequence below was hand-derived from those per-step outcomes
(box_value=10, reversal_boxes=2 — see renko_engine.py's docstring for
why 2, not 1), not generated by running the engine.
"""
from renko_engine import brick_settings, build_bricks

# S.No -> price, Table 1.5 (book, pages 24-28). "Plotting" column noted
# inline for the steps that print a brick.
RENKO_BOOK_PRICES = [
    99.15,   # 1  no plot (starting reference)
    110.20,  # 2  bullish brick
    117.05,  # 3  no plot
    110.50,  # 4  no plot
    121.85,  # 5  bullish brick
    107.00,  # 6  no plot
    124.00,  # 7  no plot
    99.90,   # 8  bearish brick
    120.80,  # 9  bullish brick
    124.55,  # 10 no plot
    115.20,  # 11 no plot
    130.90,  # 12 bullish brick
    141.75,  # 13 bullish brick
    131.65,  # 14 no plot
    152.05,  # 15 bullish brick
    159.70,  # 16 no plot
    147.10,  # 17 no plot
    160.70,  # 18 bullish brick
    169.85,  # 19 no plot
    160.90,  # 20 no plot
    175.25,  # 21 bullish brick
    182.30,  # 22 bullish brick
    188.65,  # 23 no plot
    193.75,  # 24 bullish brick
    180.05,  # 25 no plot
    164.85,  # 26 bearish brick
    157.15,  # 27 bearish brick
]

# (direction, start_price, end_price) for every resulting brick-run
# (a "column" in the reused engine), hand-derived from the per-step
# outcomes above.
EXPECTED_BRICKS = [
    ("up", 100, 120),
    ("down", 110, 100),
    ("up", 110, 190),
    ("down", 180, 160),
]


def test_book_exercise_full_brick_sequence():
    settings = brick_settings(box_value=10)
    bricks = build_bricks(RENKO_BOOK_PRICES, settings)

    actual = [(b.direction, settings.price_at(b.start_level), settings.price_at(b.end_level)) for b in bricks]
    assert actual == EXPECTED_BRICKS, f"Brick sequence diverged from the book's worked exercise.\nExpected: {EXPECTED_BRICKS}\nActual:   {actual}"


def test_book_exercise_final_state():
    settings = brick_settings(box_value=10)
    bricks = build_bricks(RENKO_BOOK_PRICES, settings)
    last = bricks[-1]
    assert last.direction == "down"
    assert settings.price_at(last.end_level) == 160


def test_reversal_needs_two_boxes_not_one():
    """Book's own explicit callout (Ch.1, brick value 5 illustration):
    with an up-run extreme at 115 (2 bricks: 100-105-110-115... in this
    exercise's brick value 10, extreme 120), the reversal brick doesn't
    print one box down (110) — it prints two boxes down (100), the low
    of the PREVIOUS brick. This is what distinguishes Renko's
    reversal_boxes=2 from a naive reversal_boxes=1 read of "one brick
    reversal"."""
    settings = brick_settings(box_value=10)
    # Extreme at 120 (up), price falls to 110.20 only — one box down,
    # must NOT reverse yet.
    bricks = build_bricks([99.15, 110.20, 121.85, 110.20], settings)
    assert bricks[-1].direction == "up"
    # Falling all the way to 99.90 (two boxes down from 120) DOES reverse.
    bricks = build_bricks([99.15, 110.20, 121.85, 99.90], settings)
    assert bricks[-1].direction == "down"


def test_first_brick_needs_only_one_box():
    """Book: 'we'll begin with a bullish brick if price goes up 10
    points' — the very first brick only needs ONE box off the starting
    reference, not the 2-box reversal distance (there's no existing
    brick to reverse from yet)."""
    settings = brick_settings(box_value=10)
    bricks = build_bricks([99.15, 110.20], settings)
    assert len(bricks) == 1
    assert bricks[0].direction == "up"
