"""
Regression test for pnf_engine.py, encoding Definedge's own fully
worked construction exercise verbatim: "Trading The Markets The Point
& Figure Way" (Prashant Shah, 2018), Ch. 1.1 - Bajaj Auto, Sept
2014-Jan 2015, 10 x 3 absolute box-value chart.

This is a primary-source ground truth, not a self-check: every single
step below (price -> resulting column state) is transcribed directly
from the book's own step-by-step narration, not derived from our
implementation. If pnf_engine.py is ever changed, this test failing
means a real behavioral regression against Definedge's own documented
construction rules, not just a different opinion.
"""
import pytest

from pnf_engine import BoxSettings, build_columns

BAJAJ_AUTO_PRICES = [
    2300,       # starting reference (book: "nothing can be done at this price")
    2339.65,    # step 1: X begins, filled to 2330
    2359.30,    # step 2: X continues to 2350
    2336.55,    # step 3: no plot
    2302.65,    # step 4: reverses to O, filled to 2310 (NOT 2300 - the book's own
                # boundary-condition callout: box 2300 needs price <= 2300 exactly)
    2320.25,    # step 5: no plot
    2412.55,    # step 6: reverses to X, filled to 2410
    2393.60,    # step 7: no plot
    2376.10,    # step 8: reverses to O, filled to 2380
    2353.65,    # step 9: continues O to 2360 (book explicitly: 2350 NOT marked)
    2412.00,    # step 10: reverses to X, filled to 2410
    2363.55,    # step 11: reverses to O, filled to 2370
    2412.60,    # step 12: reverses to X, filled to 2410 (third test of this level)
    2494.90,    # step 13: continues X to 2490
    2529.70,    # step 14: continues X to 2520 (book explicitly: 2530 NOT marked)
    2499.25,    # step 15: no plot
    2577.50,    # step 16: continues X to 2570
    2611.05,    # step 17: continues X to 2610
    2539.70,    # step 18: reverses to O, filled to 2540 (book's own boundary
                # callout: "had the price been at 2541, box-price 2540 would
                # not have been marked")
    2674.95,    # step 19: reverses to X, filled to 2670
    2644.00,    # step 20: no plot
    2517.90,    # step 21: reverses to O, filled to 2520
    2463.05,    # step 22: continues O to 2470
    2519.25,    # step 23: reverses to X, filled to 2510
    2432.45,    # step 24: reverses to O, filled to 2440
    2324.10,    # step 25: continues O to 2330 (final state)
]

# (direction, start_price, end_price) for every column the book's own
# narration produces, in order - transcribed by hand from the 25 steps
# above, not generated by running the engine.
EXPECTED_COLUMNS = [
    ("up", 2310, 2350),
    ("down", 2340, 2310),
    ("up", 2320, 2410),
    ("down", 2400, 2360),
    ("up", 2370, 2410),
    ("down", 2400, 2370),
    ("up", 2380, 2610),
    ("down", 2600, 2540),
    ("up", 2550, 2670),
    ("down", 2660, 2470),
    ("up", 2480, 2510),
    ("down", 2500, 2330),
]


def test_bajaj_auto_exercise_full_column_sequence():
    settings = BoxSettings(reversal_boxes=3, box_value=10)
    columns = build_columns(BAJAJ_AUTO_PRICES, settings)

    actual = [(c.direction, settings.price_at(c.start_level), settings.price_at(c.end_level)) for c in columns]
    assert actual == EXPECTED_COLUMNS, f"Column sequence diverged from the book's worked exercise.\nExpected: {EXPECTED_COLUMNS}\nActual:   {actual}"


def test_bajaj_auto_exercise_final_state():
    settings = BoxSettings(reversal_boxes=3, box_value=10)
    columns = build_columns(BAJAJ_AUTO_PRICES, settings)
    last = columns[-1]
    assert last.direction == "down"
    assert settings.price_at(last.end_level) == 2330


def test_first_column_needs_only_one_box_not_full_reversal():
    """Book, step 1: 'Plotting will begin with column of X if price goes
    10 points higher to 2310' - the very first column only needs ONE
    box off the starting reference, not reversal_boxes (3/30 points).
    This is different from an ongoing reversal and must not be
    conflated with it."""
    settings = BoxSettings(reversal_boxes=3, box_value=10)
    columns = build_columns([2300, 2311], settings)
    assert len(columns) == 1
    assert columns[0].direction == "up"


def test_falling_column_box_level_uses_ceiling_not_floor():
    """Book's own explicit boundary callout: with an O column open and
    box-value 10, price 2302.65 stops at box-price 2310, NOT 2300 -
    2300 would require price <= 2300 exactly. Confirms the box level
    for a falling column is a ceiling, not the naive floor(price/box)."""
    settings = BoxSettings(reversal_boxes=3, box_value=10)
    assert settings.level_down(2302.65) == 231  # -> 2310
    assert settings.level_up(2302.65) == 230    # -> 2300 (not reached going down)


def test_reversal_is_symmetric():
    """Confirmed against Definedge's shelf.definedgesecurities.com
    worked example and the book's own exercise: reversal_boxes applies
    identically whether flipping X->O or O->X - not 1 box one way and
    reversal_boxes the other."""
    settings = BoxSettings(reversal_boxes=3, box_value=10)
    # Up column at extreme 2350 (level 235): reversal to O needs a
    # ceiling-level <= 235 - 3 = 232 (2320), same 3-box distance as
    # the up->down and down->up cases throughout the Bajaj Auto test.
    up_col = build_columns([2300, 2339.65, 2359.30], settings)[-1]
    assert up_col.direction == "up" and up_col.end_level == 235
    # A move to exactly the 3-box threshold (2320) must NOT yet
    # reverse (needs to clear it, per the book's own "nothing plotted
    # unless price trades at or above/below the level" framing using
    # a strict <=/>= on the ceiling/floor, consistent with step 4
    # where 2302.65 -- past the 2320 threshold -- does reverse).
    reversed_col = build_columns([2300, 2339.65, 2359.30, 2319.99], settings)[-1]
    assert reversed_col.direction == "down"


def test_percentage_box_uses_an_absolute_price_grid():
    """Percentage/log box charts put box boundaries at FIXED prices
    (level = log(price)/log(1+box_pct)), not at offsets from wherever the
    series happens to begin.

    This test previously asserted the exact opposite, on the strength of
    an old blackbox_prism_alpha comment reporting that "a chart starting
    at 100 flipped to the next box at ~100.5, not 101" on an absolute
    grid. That observation was right; reading it as a defect was the
    mistake. A fixed grid's boundary near 100 simply isn't at 101, so
    flipping at ~100.5 is the grid working correctly.

    Falsified against a real platform chart on 2026-08-01 (NIFTY 24400
    CE, 3% x 3): under chart-relative anchoring the CURRENT COLUMN
    DIRECTION changed with the lookback - O over 3 and 7 days, X over
    15/30/60/90 - on otherwise identical parameters. See
    test_absolute_grid_is_independent_of_how_much_history_is_loaded
    below, which pins the property that actually matters."""
    settings = BoxSettings(reversal_boxes=3, box_pct=0.01)

    # The grid is absolute, so a series starting at 100 crosses its first
    # boundary just above 100 - not at 101.
    first_column = build_columns([100, 100.5], settings)
    assert len(first_column) == 1
    assert first_column[0].direction == "up"
    assert first_column[0].anchor == 1.0
    boundary = settings.price_at(first_column[0].end_level)
    assert 100 < boundary <= 100.5

    # Every box boundary is an exact power of (1 + box_pct).
    lvl = settings.level_up(100.5)
    assert settings.price_at(lvl) == pytest.approx(1.01 ** lvl)

    # The superseded behaviour is still reachable for comparison.
    relative = BoxSettings(reversal_boxes=3, box_pct=0.01, absolute_grid=False)
    assert build_columns([100, 100.5], relative) == []
    assert build_columns([100, 101], relative)[0].anchor == 100


def test_absolute_grid_is_independent_of_how_much_history_is_loaded():
    """The property the real-chart comparison actually turned on: two
    viewers looking at the same instrument over different amounts of
    history must see the SAME boxes and the same open column.

    Chart-relative anchoring cannot deliver this - trimming the front of
    the series moves the whole grid - which is how the bug was caught
    (an option premium read Bearish on a 7-day window and Bullish on a
    30-day window, same parameters, same day)."""
    series = [100, 103, 101, 106, 104, 110, 107, 112, 109, 115, 111, 118]
    settings = BoxSettings(reversal_boxes=3, box_pct=0.01)

    full = build_columns(series, settings)
    trimmed = build_columns(series[4:], settings)

    # Same grid: the open column has the same direction and sits at the
    # same box level. Its START level may legitimately differ - the
    # trimmed series never saw that column open - but the EXTREME, which
    # is what every signal and reversal level is measured from, must not
    # move, and a given level must mean the same price in both.
    assert full[-1].direction == trimmed[-1].direction
    assert full[-1].end_level == trimmed[-1].end_level
    assert settings.price_at(full[-1].end_level) == settings.price_at(trimmed[-1].end_level)

    # And the same is NOT true of the superseded anchoring: there the
    # extreme itself moves, so the reversal level moves with it.
    relative = BoxSettings(reversal_boxes=3, box_pct=0.01, absolute_grid=False)
    rel_full = build_columns(series, relative)
    rel_trimmed = build_columns(series[4:], relative)
    assert (rel_full[-1].anchor != rel_trimmed[-1].anchor)
    assert (settings.price_at(rel_full[-1].end_level, rel_full[-1].anchor)
            != settings.price_at(rel_trimmed[-1].end_level, rel_trimmed[-1].anchor))


def test_float_error_at_an_exact_boundary_does_not_lose_a_box():
    """A price that's mathematically exactly N boxes from the anchor can
    still land a hair under N due to float rounding
    (log(102.01/100)/log(1.01) computes to 1.999999999999999, not 2.0) -
    caught while wiring this engine into blackbox_prism_alpha.py, which
    had its own epsilon guard for exactly this before being switched
    over to share this engine. 102.01 is precisely 100 * 1.01^2 - two
    full boxes above the 100 anchor - and must register as level 2, not
    1."""
    settings = BoxSettings(reversal_boxes=3, box_pct=0.01)
    assert settings.level_up(102.01, anchor=100) == 2
