import { useEffect, useState } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { ArrowUpRight, TrendingUp } from "lucide-react";
import Navbar from "../components/site/Navbar";
import Footer from "../components/site/Footer";
import ParticleField from "../components/site/ParticleField";
import Reveal from "../components/site/Reveal";
import BiasBadge from "../components/site/BiasBadge";
import { scrollToId } from "../components/site/SmoothScroll";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const EASE = [0.16, 1, 0.3, 1];

const SCANNER_ORDER = [
  { key: "momentum", label: "Momentum Leaders" },
  { key: "relative_strength", label: "Relative Strength Leaders" },
  { key: "breakout", label: "Breakout Candidates" },
  { key: "positional", label: "Positional Opportunities" },
];

const DISCLAIMER =
  "Data generated by Sapphire Alpha Capital's proprietary quantitative models. This information is intended solely for research and educational purposes and does not constitute investment advice.";

const MomentumTable = ({ rows }) => (
  <div className="glass rounded-2xl overflow-hidden" data-testid="momentum-table">
    <div className="overflow-x-auto">
      <table className="w-full min-w-[720px] text-left">
        <thead>
          <tr className="border-b border-white/10">
            {["Ticker", "Company", "Momentum Score", "Volume", "Bias"].map((h) => (
              <th key={h} className="px-6 py-5 font-mono-ui text-[11px] uppercase tracking-[0.18em] text-slate-500 font-semibold whitespace-nowrap">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <motion.tr
              key={r.id}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: EASE, delay: i * 0.06 }}
              className="border-b border-white/[0.05] last:border-0 transition-colors duration-300 hover:bg-sapphire/[0.06]"
              data-testid={`momentum-row-${i}`}
            >
              <td className="px-6 py-5 whitespace-nowrap">
                <span className="inline-flex items-center gap-1.5 font-display text-lg font-extrabold text-white tracking-tight">
                  {r.ticker}
                  <TrendingUp size={14} className="text-emerald-400" />
                </span>
              </td>
              <td className="px-6 py-5 text-sm text-slate-300 whitespace-nowrap">{r.company || "—"}</td>
              <td className="px-6 py-5">
                <span className="inline-flex items-center rounded-md border border-emerald-400/25 bg-emerald-400/10 px-2.5 py-1 font-mono-ui text-sm font-semibold text-emerald-300">
                  {r.momentum_score}
                </span>
              </td>
              <td className="px-6 py-5 font-mono-ui text-sm text-slate-300 whitespace-nowrap">{r.volume}</td>
              <td className="px-6 py-5"><BiasBadge bias={r.bias} testid={`momentum-bias-${i}`} /></td>
            </motion.tr>
          ))}
        </tbody>
      </table>
    </div>
    <div className="px-6 py-5 border-t border-white/10">
      <p className="text-xs font-light text-slate-500 leading-relaxed max-w-4xl" data-testid="momentum-disclaimer">
        {DISCLAIMER}
      </p>
    </div>
  </div>
);

const ComingSoonCard = ({ scannerKey }) => (
  <div
    className="group glass rounded-2xl border border-white/10 px-6 py-20 md:py-28 flex flex-col items-center justify-center text-center transition-colors duration-500 hover:border-sapphire/40 hover:bg-sapphire/[0.03]"
    data-testid={`coming-soon-${scannerKey}`}
  >
    <span className="font-mono-ui text-[11px] uppercase tracking-[0.28em] text-slate-600 mb-4 transition-colors duration-500 group-hover:text-sapphire-light">
      In Development
    </span>
    <h4 className="font-display text-2xl md:text-3xl font-bold text-slate-300">Coming Soon</h4>
    <p className="mt-3 text-sm font-light text-slate-500 max-w-sm">
      This scanner is being calibrated and will activate here as soon as it goes live.
    </p>
  </div>
);

const ScannerSection = ({ label, scannerKey, rows, index }) => (
  <Reveal delay={0.05} className="mb-16 md:mb-24" data-testid={`scanner-${scannerKey}`}>
    <div className="flex items-center gap-4 mb-6">
      <span className="font-mono-ui text-xs text-sapphire-light">{String(index + 1).padStart(2, "0")}</span>
      <h3 className="font-display text-2xl md:text-3xl font-bold text-white tracking-tight">{label}</h3>
      <span className="h-px flex-1 bg-white/10" />
    </div>
    {rows && rows.length > 0 ? <MomentumTable rows={rows} /> : <ComingSoonCard scannerKey={scannerKey} />}
  </Reveal>
);

export default function AlphaTerminal() {
  const [data, setData] = useState({});
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
    axios
      .get(`${API}/terminal/stocks`)
      .then((r) => {
        const grouped = {};
        r.data.forEach((s) => {
          grouped[s.scanner] = grouped[s.scanner] || [];
          grouped[s.scanner].push(s);
        });
        setData(grouped);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <Navbar />
      <main className="relative bg-void min-h-screen">
        {/* Hero */}
        <section className="relative pt-36 pb-16 md:pt-44 md:pb-20 overflow-hidden" data-testid="terminal-hero">
          <ParticleField density={0.00006} />
          <div className="absolute inset-0 radial-glow" />
          <div className="absolute inset-0 bg-gradient-to-b from-void/0 to-void pointer-events-none" />
          <div className="container-x relative z-10">
            <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-8">
              <div className="max-w-2xl">
                <motion.div
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.7, ease: EASE }}
                  className="flex items-center gap-3 mb-6"
                >
                  <span className="relative flex h-2 w-2">
                    <span className="absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75 animate-ping" />
                    <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400" />
                  </span>
                  <span className="font-mono-ui text-[11px] uppercase tracking-[0.28em] text-emerald-300 font-bold">
                    Live Alpha Terminal
                  </span>
                </motion.div>
                <motion.h1
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.9, ease: EASE, delay: 0.1 }}
                  className="font-display font-black tracking-tighter text-white text-5xl md:text-7xl leading-[0.95]"
                >
                  Alpha Terminal
                </motion.h1>
                <motion.p
                  initial={{ opacity: 0, y: 24 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.9, ease: EASE, delay: 0.2 }}
                  className="mt-6 text-base md:text-lg font-light text-slate-400 leading-relaxed"
                  data-testid="terminal-subtitle"
                >
                  Real-time quantitative market intelligence generated by Sapphire Alpha
                  Capital&apos;s proprietary screening models.
                </motion.p>
              </div>

              <motion.div
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, ease: EASE, delay: 0.3 }}
                className="glass rounded-full px-5 py-3 inline-flex items-center gap-3 self-start lg:self-auto"
                data-testid="terminal-updated"
              >
                <span className="h-2.5 w-2.5 rounded-full bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,0.7)]" />
                <span className="font-mono-ui text-xs text-slate-300">
                  Updated: <span className="text-white">Today, 09:30 AM IST</span>
                </span>
              </motion.div>
            </div>
          </div>
        </section>

        {/* Scanners */}
        <section className="relative pb-28 md:pb-40">
          <div className="container-x">
            {loading ? (
              <div className="flex items-center justify-center py-32 text-slate-500 font-mono-ui text-sm gap-3" data-testid="terminal-loading">
                <span className="h-2 w-2 rounded-full bg-sapphire-light animate-ping" /> Loading terminal…
              </div>
            ) : (
              SCANNER_ORDER.map((s, i) => (
                <ScannerSection
                  key={s.key}
                  label={s.label}
                  scannerKey={s.key}
                  rows={data[s.key]}
                  index={i}
                />
              ))
            )}

            <Reveal className="mt-8">
              <a
                href="/#waitlist"
                onClick={(e) => { e.preventDefault(); navigate("/"); setTimeout(() => scrollToId("waitlist"), 550); }}
                className="inline-flex items-center gap-2 text-sapphire-light hover:text-white transition-colors text-sm font-medium"
                data-testid="terminal-subscribe-link"
              >
                Subscribe for daily lists <ArrowUpRight size={15} />
              </a>
            </Reveal>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
